### ISSUE TITLE
Code in markdown files for project 1 submission. 

### ISSUE THREAD

**Issue by tweedya** [STA518-01-W21/community#10]
Allowing the code to echo in the markdown document seems to have a negative impact on the presentation quality of the document. Should we leave the code echo enabled for grading purposes or can/should we disable it?

**Comment by dykesb** [comment]
Remember that questions related to projects (and also learning target completion related) must be emailed to me. If I feel that it is general enough, I would then point you to ask it here. When you send me an email, please include examples of what is being negatively impacted.

**Comment by dykesb** [comment]
In follow-up, this was about whether to display code and output (vs just output) in knitted reports. I want to see both (this is the default behavior) so that I can provided more direct comments if needed.
