### ISSUE TITLE
Learning Target Check 1: DW.3 Clarity Update

### ISSUE THREAD

**Issue by dykesb** [STA518-01-W21/community#11]
If you already cloned the LTC, I have made an edit to DW.3 to hopefully be more clear. Originally, the statement was:

> Create a tibble with a new column `family_name_length` that contains the lengths of each family names. Save this in a variable called `lengths`. You do not need to assign this tibble to anything.

This has be updated to be:

> Create a tibble with a new column `family_name_length` that contains the lengths of each family names. You do not need to assign this tibble to anything.

If you have not yet created the LTC repo, this should be fixed when you do so.

**Comment by dykesb** [comment]
Further clarification for the `sorted_name_length` code chunk prompt. Originally the statement was:

> Display all the rows in `lengths` sorted by family name length with the longest name first. You do not need to assign this tibble to anything.

This has been updated to be: 

> Display all the rows `person` (including `family_name_length`), sorted by family name length with the longest name first. You do not need to assign this tibble to anything.

**Comment by amarkules-gvsu** [comment]
@dykesb if we submitted the learning target check prior to this revision, should we pull the updated version into our assignment and make changes?

**Comment by dykesb** [comment]
If you correctly interpreted my original directions, there is nothing additional that you need to do. If this update changes how you worked this task, I would recommend that you make the changes directly in your copy - I think pulling between my version and your clone is not possible.
