### ISSUE TITLE
Learning Target Check Citations

### ISSUE THREAD

**Issue by amarkules-gvsu** [STA518-01-W21/community#12]
Hi Bradford,
For resources we use in the learning target checks, is there any standard format you'd like for citing resources? Is including a link to the resource where it's being used acceptable? Or would you like a more formal citation somewhere?

Thanks,
Alex

**Comment by dykesb** [comment]
There is no specific format that you need to post the resources as (e.g., APA vs. MLA) and it really does not need to be super formal. That is, you could simply note the resource your found it at (e.g., [regular expression help](https://regexr.com/)). When you provide a citation, also include details for HOW that resource helped you - don't leave it up to me to guess as to what you used it for.

**Comment by amarkules-gvsu** [comment]
Thanks Bradford! So would it be sufficient if I include a comment in the .Rmd file saying something like "I wasn't sure how to add a title to a ggplot, so I used this resource to help: resource url"?
