### ISSUE TITLE
Prep 10 data

### ISSUE THREAD

**Issue by austinpfiffner** [STA518-01-W21/community#15]
For prep 10 doing the r studio thing. How do you get the starwars dataset? It says it is in stringr but when I try to do stringr:: the only data sets that come up is the fruit, sentences, or words datasets. Let me know if I am doing something wrong.

**Comment by dykesb** [comment]
If you've loaded the `{tidyverse}`, you should be able to call it by typing `starwars` like when we assign a data file to an R object when reading it in. Sorry for the confusion.
