### ISSUE TITLE
Trying to convert date in rat sightings to date format

### ISSUE THREAD

**Issue by liam-hart** [STA518-01-W21/community#18]
_rat_sightings <- rat_sightings %>%
  select(`Unique Key`, `Created Date`, `Closed Date`, `Agency Name`, City, Borough) %>%
  mutate(`Created Date` = str_sub(`Created Date`, 1, 10)) %>%
  mutate(`Closed Date` = str_sub(`Closed Date`, 1, 10)) %>%
  drop_na(`Created Date`) %>%
  drop_na(`Closed Date`)

rat_sightings %>%
  as.Date(`Created Date`, format = "%m%d%y") %>%
  as.Date(`Closed Date`, format = "%m%d%y")_

This my code where I am trying to convert the character variables of Created Date and Closed Date into date format so I can plot the difference in time using difftime(). This is the error it gives me:

Error in as.Date.default(., `Created Date`, format = "%m%d%y") : do not know how to convert '.' to class “Date”

I am assuming that this means the date column needs to be cleaned up but I am unsure how to check if this is the case and unsure how to drop or change these observations.

**Comment by dykesb** [comment]
Not sure if the `_` at the start and end of your code are meant to to indicate code of if this is actually part of your code. If it is supposed to designate a code chunk, you should use three backticks (```) above and below the code.

It looks like you are trying to *convert* a variable within `rat_sightings`. Remember that this should be done within a `mutate` line.
