### ISSUE TITLE
First class

### ISSUE THREAD

**Issue by Barthur006** [STA518-01-W21/community#2]
Hello Dr Bradford,

I would like to ask if the recorded class section would be posted on BB but if not can I get the recording for further studies and understand.

Thank you

**Comment by dykesb** [comment]
All class session recordings will be available in the same place that you access the Bb Collaborate sessions:

- In the Bb course site, click on **Bb Collaborate Sessions MW 4-5:15pm**
- On Bb Collaborate Ultra page, click on hamburger-icon (three horizontal lines in upper left-hand corner)
- Click on Recordings in the Bb Collaborate menu
