### ISSUE TITLE
LTC4: State Names vs State Codes in DW.4

### ISSUE THREAD

**Issue by amarkules-gvsu** [STA518-01-W21/community#20]
While working on DW.4 in LTC 4, I saw that you want us to join the avocado data and the death row data by state. Normally this would be easy enough, but the avocado regions data uses 2 letter state codes while the death row data uses full state names. Do you expect us to pull in another dataset not included in the learning target check in order to accomplish this join? Or is there some other means of joining them that I'm missing?

**Comment by dykesb** [comment]
I meant to include a comment along the lines of, but forgot to include:

> You may find the built-in R `state.*` objects helpful for this task
