### ISSUE TITLE
Session Agenda/Video Request

### ISSUE THREAD

**Issue by dykesb** [STA518-01-W21/community#3]
This Issue will remain open for the semester. You can use this to post items that you:
- Want me to address live for the upcoming class session, or 
- Would like a video explanation detailing concepts or doing a coding demonstration

**Comment by knoppj** [comment]
I was hoping to get an explanation of exercise 2 in 12.2.1 Exercises.  It's somewhat frustrating that the text posts these exercises but (unless I'm missing it) doesn't post solutions.
