### ISSUE TITLE
Hypothesis confirmation

### ISSUE THREAD

**Issue by treed8887** [STA518-01-W21/community#5]
@dykesb, I noticed in the textbook that hypothesis confirmation is not covered because "You need a precise mathematical model in order to generate falsifiable predictions. This often requires considerable statistical sophistication."

Would you know if it's covered in higher level STA courses in the DSA program?

**Comment by dykesb** [comment]
I would say that most other STA courses (e.g., STA 631 and STA 526/623) focus on some aspect of hypothesis confirmation and/or parameter estimation: testing hypotheses about population parameters or constructing confidence intervals. We will do some bootstrapping/resampling methods of hypothesis confirmation later in the course. CIS 635 might cover this some with clustering/discrimination too.
