### ISSUE TITLE
Activity due dates. 

### ISSUE THREAD

**Issue by Jockusct** [STA518-01-W21/community#6]
I had a question about the activities. In today's activity, Activity 1.3, my group and I were not able to complete it all the way since we got hung up on trying to figure out some github and rstudio linking issues. Because of this, would the activity we did today and activities going further be something we should do on our own and complete by a certain point of the week if we do not finish it in class?

**Comment by dykesb** [comment]
Typically one of the activities that we work on during a week will be submitted as a follow-up assignment (due by 11:59 pm on Sunday) as a clickable link on Blackboard. I check these for effort from each member (not correctness) and will not be too concerned with doing the pull requests and merge conflicts.

This week's follow-up will be Activity 1.3 and I will create the item on Blackboard tomorrow morning. One of your team will need to submit a link to your team's Activity 1.3 repo. Note that you can always submit this link early and continue making changes on your repo after the fact.

In future weeks, I hope to prioritize class time working on activities and not requiring as much to be completed outside of class. Also, the "git-ing" started process will start to become a habit which will also help with us progressing through the materials.
