### ISSUE TITLE
Using instructor-provided solutions in activity follow-up submissions

### ISSUE THREAD

**Issue by devinkolff** [STA518-01-W21/community#8]
I was wondering if we were able to use the answer sheet that was posted on blackboard as a reference if we couldn’t figure out how to do one of the problems?

**Comment by dykesb** [comment]
@devinkolff I see this as two separate questions. Can you make this two separate issues (you can edit this to be one of them)? I would like to keep this area easy to search and each issue focused on one item.

**Comment by dykesb** [comment]
Remember that I will not be checking activities for correctness, but rather effort and turning it in on time. In general, activities are *your* notes. If you needed to use my solution to answer an item make a note about what was confusing and how my solution helped.
