### ISSUE TITLE
Pushing activities with errors

### ISSUE THREAD

**Issue by devinkolff** [STA518-01-W21/community#9]
I was wondering if we should only commit and push our code if there were no problems with our code, or are we still able to commit and push it even if some of our answers for questions 1-13 on task 4 don’t work as they’re intended to?

**Comment by dykesb** [comment]
An activities doesn't need to be "complete" to be pushed to GitHub. If you do not complete everything by the "due date" for a follow-up, that is ok. However, you are still responsible for the information contained in the activities. If something is confusing or problematic, reach out for help in the many forms available to you. 

Now, if an activity has many blank spots, that is not an honest effort. Not attempting everything is different than not knowing how to do something. Show your current understanding, try something, then reach out for help.
